### PR TITLE
fix: added SKU to the products array

### PR DESCRIPTION
**Pull request by dbelkad**
### PR CHECKLIST

- [x] All translations are concatenated with an EOT character between the translation context and key (ie. `backend/config[EOT]general_settings_header`)
- [x] The version information documented in the readme.txt has been manually updated in line with semantic versioning
- [x] The readme file's Changelog has been updated with your proposed PR
- [x] The version information in `class-wc-gateway-finance.php` (included within the initial docblock and the start of the constructor) has been updated

### CODE REVIEW

**Review by joelbitar — CHANGES_REQUESTED** [review]
version needs to be updated in the comment block at the begining och the file and in constructor

**Review by simeon-anastasov-divido — APPROVED** [review]
The version was bumped as requested.

**Review by dbelkad — COMMENTED** [review]
Done

**Review by joelbitar — APPROVED** [review]
👍

**Pull request merged**
